-- MySQL Script generated by MySQL Workbench
-- Mon Oct  9 12:39:51 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema articles
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema articles
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `articles` DEFAULT CHARACTER SET utf8 ;
USE `articles` ;

-- -----------------------------------------------------
-- Table `articles`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `articles`.`articles` (
  `title` VARCHAR(70) NOT NULL,
  `author` VARCHAR(45) NULL,
  `contents` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`title`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `articles`.`articles`
-- -----------------------------------------------------
START TRANSACTION;
USE `articles`;
INSERT INTO `articles`.`articles` (`title`, `author`, `contents`) VALUES ('TEST', 'Tester', NULL);

COMMIT;

